rent_app/rent_app/book_site/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('', views.home_redirect, name='home_redirect'),
    path('catalogue', views.catalogue, name='catalogue'),
    path('catalogue', views.catalogue_redirect, name='catalogue_redirect'),
    path('profile', views.profile, name='profile'),
    path('profile', views.profile_redirect, name='profile_redirect'),
    path('login', views.login_view, name='login'),
    path('login', views.login_redirect, name='login_redirect'),
    path('register', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('confirmRegistration', views.confirmRegistration, name='confirmRegistration'),
    path('successfulVerification', views.successfulVerification, name='successfulVerification'),
    path('password_reset/', views.password_reset1, name='password_reset1'),
    path('password_reset/', views.password_reset_redirect, name='password_reset1_redirect'),
    path('password_reset/done1/', views.password_reset_done1, name='password_reset_done1'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm1, name='password_reset_confirm1'),
    path('reset/done/', views.password_reset_complete1, name='password_reset_complete1'),
    path('book/<int:book_id>/', views.book_details, name='book_details'),
    path('reserve_book/<int:book_id>/', views.reserve_book, name='reserve_book'),
    path('reserve_book/notLogged', views.reserve_not_logged, name='reserve_not_logged'),
    path('cancel_reservation/<int:reservation_id>/', views.cancel_reservation, name='cancel_reservation'),
    path('profile/settings', views.profile_settings_view, name='profile_settings_view'),
    path('profile/reviews', views.profile_reviews_view, name='profile_reviews_view'),
    path('cancel_review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('profile/reviews/export/', views.export_to_excelReview, name='export_to_excelReview'),
    path('profile/reservations/export/', views.export_to_excelReservation, name='export_to_excelReservation'),

]

rent_app/rent_app/rent_app/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include

urlpatterns = [
    path('', lambda request: HttpResponseRedirect('/book_site/')),
    path("admin/", admin.site.urls),
    path('book_site/', include('book_site.urls')),
    path("book_site/", include("django.contrib.auth.urls")),
]

rent_app/rent_app/book_site/models.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.shortcuts import get_object_or_404
from django.utils import timezone


class Book(models.Model):
    title = models.CharField(max_length=127)
    author = models.CharField(max_length=31)
    available = models.BooleanField()
    pub_date = models.DateField()
    date_added = models.DateField(auto_now_add=True)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=12, validators=[
        RegexValidator(regex='^\d{9}$', message='Phone number must be 9 digits', code='invalid_phone_number')])
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)


class BookReview(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
    review_text = models.TextField()
    stars = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1, 6)])
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='book_reviews')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review by {self.user.username} on {self.book.title}'


class Reservation(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reserved_at = models.DateTimeField(auto_now_add=True)
    pickup_date = models.DateTimeField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"Reservation for {self.book.title} by {self.user.username}"

    def is_valid(self):
        if self.pickup_date >= timezone.now() and self.is_active:
            book = get_object_or_404(Book, id=self.book.id)

            book.available = False
            book.save()
            return True
        else:
            book = get_object_or_404(Book, id=self.book.id)

            book.available = True
            book.save()

            return False


class BookReviewAdmin(admin.ModelAdmin):
    list_display = ('book', 'user', 'stars', 'created_at')
    search_fields = ('book__title', 'user__username')
    list_filter = ('stars', 'created_at')


class BookAdmin(admin.ModelAdmin):
    list_display = ('title', 'author', 'available', 'pub_date', 'date_added')
    search_fields = ('title', 'author')
    list_filter = ('available', 'pub_date')
    ordering = ('-date_added',)
    fields = ('title', 'author', 'available', 'pub_date')
    list_display_links = ('title', 'author')


class UserProfileAdmin(admin.ModelAdmin):
    list_display = ('user', 'phone_number', 'country', 'city')
    search_fields = ('user__username', 'phone_number', 'country', 'city')


class ReservationAdmin(admin.ModelAdmin):
    list_display = ('book', 'user', 'reserved_at', 'pickup_date', 'is_active')
    list_filter = ('is_active', 'reserved_at', 'pickup_date')
    search_fields = ('book__title', 'user__username')


admin.site.register(Reservation, ReservationAdmin)

admin.site.register(UserProfile, UserProfileAdmin)

admin.site.register(Book, BookAdmin)

admin.site.register(BookReview, BookReviewAdmin)

rent_app/rent_app/book_site/forms.py
# forms.py
from django import forms

from book_site.models import BookReview, Reservation
from book_site.widgets import StarRatingWidget


class SetNewPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput, label="New password", min_length=8)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Confirm password", min_length=8)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data


class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview

        fields = ['review_text', 'stars']
        widgets = {'review_text': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write your review here...'}),
                   'stars': StarRatingWidget, }

    def is_valid(self):
        if not super().is_valid():
            return False
        cleaned_data = super().clean()

        review_text = cleaned_data.get("review_text")
        stars = cleaned_data.get("stars")
        if not review_text or not stars:
            return False
        return True


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['book']

    def clean(self):
        cleaned_data = super().clean()
        book = cleaned_data.get('book')

        if Reservation.objects.filter(book=book).exists():
            raise forms.ValidationError("This book is already reserved.")

        return cleaned_data

rent_app/rent_app/book_site/views.py
from datetime import timedelta, datetime

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from openpyxl import Workbook

from book_site.create_account_form import UserRegistrationForm
from book_site.forms import SetNewPasswordForm, BookReviewForm
from book_site.models import Book, Reservation, UserProfile
from .models import BookReview


def index(request):
    return render(request, 'book_site/index.html')


def home_redirect(request):
    return HttpResponseRedirect('book_site/')


def profile_redirect(request):
    return HttpResponseRedirect('login')


def login_redirect(request):
    return HttpResponseRedirect('login')


def catalogue_redirect(request):
    return HttpResponseRedirect('catalogue/')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('profile_redirect')
    else:
        form = AuthenticationForm()
    return render(request, 'book_site/log_panel.html', {'form': form})


@login_required
def profile(request):
    if not request.user.is_authenticated:
        return redirect('login_redirect')
    else:
        reservations = Reservation.objects.filter(user=request.user)
        for reservation in reservations:
            reservation.is_valid = reservation.is_valid()
        context = {
            'reservations': reservations,
        }
        return render(request, 'book_site/profile.html', context)


def confirmRegistration(request):
    return render(request, 'book_site/info_email_sent.html')


def successfulVerification(request):
    return render(request, 'book_site/info_verification_success.html')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(str(user.pk).encode('utf-8'))
            domain = get_current_site(request).domain
            link = f'http://{domain}/book_site/activate/{uid}/{token}/'
            mail_subject = 'Potwierdź swój e-mail'
            message = render_to_string('book_site/activation_email.html', {
                'user': user,
                'link': link,
            })
            send_mail(mail_subject, message, 'admin@bookToGO.com', [user.email])

            return redirect('confirmRegistration')
    else:
        form = UserRegistrationForm()

    return render(request, 'book_site/sign_up_panel.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('successfulVerification')
    else:
        if user is not None:
            user.delete()
        messages.error(request, "Link is inactive.")
        return redirect('register')


def catalogue(request):
    reservations = Reservation.objects.all()
    for reservation in reservations:
        reservation.is_valid = reservation.is_valid()
    query = request.GET.get('search')
    criteria = request.GET.get('criteria', 'title')
    if query:
        if criteria == 'title':
            books = Book.objects.filter(Q(title__icontains=query))
            paginator = Paginator(books, 10)
        elif criteria == 'author':
            books = Book.objects.filter(Q(author__icontains=query))
            paginator = Paginator(books, 10)
        else:
            books = Book.objects.all()
            paginator = Paginator(books, 10)
    else:
        books = Book.objects.all()
        paginator = Paginator(books, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'book_site/catalogue.html', context={'page_obj': page_obj})


def password_reset_redirect(request):
    return HttpResponseRedirect('password_reset/')


def password_reset1(request):
    error_message = None
    print('start')
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        print('post')
        if form.is_valid():
            email = form.cleaned_data['email']
            print(email)
            try:
                user = User.objects.get(email=email)
                token = default_token_generator.make_token(user)
                uid = user.pk
                domain = get_current_site(request).domain
                reset_link = request.build_absolute_uri(f'http://{domain}/book_site/reset/{uid}/{token}/')
                send_mail(
                    'Reset your password',
                    f'Click the link to reset your password: {reset_link}',
                    'noreply@mywebsite.com',
                    [email]
                )
                messages.success(request,
                                 'If the email address is associated with an account, we have sent a reset link.')
                return redirect('password_reset_done1')
            except User.DoesNotExist:
                print("except")
                error_message = 'No account found with that email address.'
        else:
            error_message = 'No account found with that email address'
    else:
        form = PasswordResetForm()
    return render(request, 'registration1/password_reset.html', {'form': form,
                                                                 'error_message': error_message})


def password_reset_done1(request):
    return render(request, 'registration1/password_reset_done.html')


def password_reset_confirm1(request, uidb64, token):
    try:
        uid = int(uidb64)
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            form = SetNewPasswordForm(request.POST)
            if form.is_valid():
                new_password = form.cleaned_data['new_password']
                user.set_password(new_password)
                user.save()

                messages.success(request, 'Your password has been successfully reset!')
                return redirect('login_redirect')
        else:
            form = SetNewPasswordForm()

        return render(request, 'registration1/password_reset_confirm.html', {'form': form})
    else:
        messages.error(request, 'The link is invalid or has expired.')
        return redirect('password_reset1')


def password_reset_complete1(request):
    return render(request, 'registration1/password_reset_complete.html')


def book_details(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    reviews = BookReview.objects.filter(book=book)
    review_to_edit = None

    if request.method == 'POST':
        if 'delete_review' in request.POST:
            review_id = request.POST.get('review_id')
            review = get_object_or_404(BookReview, pk=review_id, user=request.user)
            review.delete()
            return redirect('book_details', book_id=book.id)
        else:
            review_id = request.POST.get('review_id')
            if review_id:
                review = get_object_or_404(BookReview, pk=review_id, user=request.user)
                form = BookReviewForm(request.POST, instance=review)
                review_to_edit = review
            else:
                form = BookReviewForm(request.POST)

            user_reviewed = BookReview.objects.filter(book=book, user=request.user).exists()

            if user_reviewed and not review_id:
                form.add_error(None, "You have already reviewed this book.")
            else:
                if form.is_valid():
                    review = form.save(commit=False)
                    review.book = book
                    review.user = request.user
                    review.save()

                    return redirect('book_details', book_id=book.id)
                else:
                    form.add_error(None, "You need to choose a star rating")
    else:
        review_id = request.GET.get('review_id')
        if review_id:
            review = get_object_or_404(BookReview, pk=review_id, user=request.user)
            form = BookReviewForm(instance=review)
            review_to_edit = review
        else:
            form = BookReviewForm()

    context = {
        'book': book,
        'reviews': reviews,
        'form': form,
        'review_to_edit': review_to_edit,
    }
    return render(request, 'book_site/book_details.html', context)


@login_required
def reserve_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if not book.available:

rent_app/rent_app/book_site/templates/book_site/activation_email.html
Hi {{ user.username }},
Please confirm your email address by clicking the link below:
<a href="{{ link }}">Confirm Email</a>

rent_app/rent_app/book_site/templates/book_site/book_details.html
{% extends "book_site/base.html" %}

{% block content %}
    <div class="GoBackDIV"><a href="{% url 'catalogue' %}" class="btn-btn-info">go back</a></div>
    <div class="header_Details">
        <h2>{{ book.title }}</h2>
        <p class="author_Det">{{ book.author }}</p>
    </div>
    <div class="book_Details">
        <p><strong>Published Date:</strong> {{ book.pub_date }}</p>
        <p><strong>Added to the Catalogue:</strong> {{ book.date_added }}</p>
        <p><strong>Is available?:</strong> {{ book.available }}</p>
    </div>
    <h3>Reviews:</h3>
    {% if reviews %}
        <ul class="Reviews">
            {% for review in reviews %}
                <li>
                    <div class="reviewHeader">
                        <p class="username">{{ review.user.username }}</p>

                        <p class="stars">
                            {% if review.stars == 5 %}
                                ★★★★★
                            {% elif review.stars == 4 %}
                                ★★★★☆
                            {% elif review.stars == 3 %}
                                ★★★☆☆
                            {% elif review.stars == 2 %}
                                ★★☆☆☆
                            {% elif review.stars == 1 %}
                                ★☆☆☆☆
                            {% else %}
                                No rating
                            {% endif %}
                        </p>
                    </div>
                    <p class="text">{{ review.review_text }}</p>
                    {% if user.is_authenticated and review.user == user %}
                        <div class="editButtonsDIV">
                            <form method="get" action="{% url 'book_details' book.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="review_id" value="{{ review.id }}">
                                <button type="submit" class="ReviewButtons">Edit</button>
                            </form>
                            <form method="post" action="{% url 'book_details' book.id %}"
                                  onsubmit="return confirm('Are you sure you want to delete this review?');">
                                {% csrf_token %}
                                <input type="hidden" name="review_id" value="{{ review.id }}">
                                <button type="submit" name="delete_review" class="ReviewButtons">Delete</button>
                            </form>
                        </div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="noReviews">No reviews yet.</p>
    {% endif %}

    {% if user.is_authenticated %}
        {#        <h3>Write a Review:</h3>#}
        <h4>{% if review_to_edit %}Edit{% else %}Write{% endif %} a Review:</h4>
        <form method="post" class="ReviewForm">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="errorlist">
                    {% for error in form.non_field_errors %}
                        <p class="errorReset">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="ReviewFormDiv">

                <div class="ReviewFormTextDiv">
                    <label for="id_stars">Rating:</label>
                    {{ form.stars }}
                </div>

                <div class="ReviewFormTextDiv">
                    <label for="review_text">Review:</label> {{ form.review_text }}
                </div>
                {% if review_to_edit %}
                    <input type="hidden" name="review_id" value="{{ review_to_edit.id }}">
                {% endif %}
            </div>
            <button type="submit">{% if review_to_edit %}Update{% else %}Submit{% endif %} Review</button>
        </form>
    {% else %}
        <div>
            <p class="noReviews">You must be logged in to write a review.</p>
            <div class="NotLoggedReviewDIV">
                <a href="{% url 'login_redirect' %}" class="btn-btn-info">Log in here</a>
            </div>
        </div>
    {% endif %}

{% endblock %}



rent_app/rent_app/book_site/templates/book_site/catalogue.html
{% extends "book_site/base.html" %}

{% block content %}
    <div class="container">
        <div class="top-section">
            <h2 class="header-Catalogue">Search the Catalogue</h2>

            <form method="GET" action="" id="catalogue-form">
                <input type="text" class="Catalogue-search" id=search value="{{ request.GET.search }}" name="search"
                       placeholder="Search...">
                <label class="Catalogue-search-label" for="criteria">by</label>
                <select id="criteria" class="Catalogue-search" name="criteria">
                    <option value="title" {% if criteria == 'title' %}selected{% endif %}>Title</option>
                    <option value="author" {% if criteria == 'author' %}selected{% endif %}>Author</option>
                </select>
                <button type="submit">Search</button>

                <script type="text/javascript"> document.addEventListener('DOMContentLoaded', function () {
                    const reserveButtons = document.querySelectorAll('.reserveButton_not');
                    reserveButtons.forEach((button) => {
                        button.removeEventListener('click', handleButtonClick);
                        button.addEventListener('click', handleButtonClick);
                    });

                    function handleButtonClick(event) {
                        const isLoggedIn = '{{ user.is_authenticated }}';
                        if (isLoggedIn === 'False') {
                            if (confirm('You have to be logged-in to reserve a book.\n' + 'Do you want to log in now?')) {
                                document.location = "{% url 'login_redirect' %}";
                            }
                        } else {
                            alert('Reservation successful!');
                        }
                    }
                });
                </script>

            </form>
        </div>
        <table>
            <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Reserve</th>
                <th>Details</th>
            </tr>
            </thead>
            <tbody>
            {% for book in page_obj %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>
                        {% if book.available %}
                            {% if user.is_authenticated %}
                                <form action="{% url 'reserve_book' book.id %}" method="post"
                                      onsubmit="return confirm('Are you sure you want to reserve this book?');">
                                    {% csrf_token %}
                                    <button type="submit" class="reserveButton">Reserve</button>
                                </form>
                            {% else %}
                                <button id="reserve-button" class="reserve-button reserveButton_not">Reserve</button>
                            {% endif %}
                        {% else %}
                            <button disabled class="reserveButton_notAv">Not Available</button>
                        {% endif %}
                    <td>
                        <div class="DetailsButtonCatDIV">
                            <a href="{% url 'book_details' book.id %}" class="btn-btn-info">View Details</a>
                        </div>
                    </td>
                </tr>
            {% endfor %} </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_previous %}
                    <div class="paginationLinks">
                        <div class="LinksCatalogue">
                            <a href="?search={{ request.GET.search }}&criteria={{ request.GET.criteria }}&page=1"
                               class="pagination-link">&laquo; first</a>
                        </div>
                        <div class="LinksCatalogue">
                            <a href="?search={{ request.GET.search }}&criteria={{ request.GET.criteria }}&page={{ page_obj.previous_page_number }}"
                               class="pagination-link">previous</a>
                        </div>
                    </div>
                {% endif %}

                {% if page_obj.has_next %}
                    <div class="paginationLinks">
                        <div class="LinksCatalogue">
                            <a href="?search={{ request.GET.search }}&criteria={{ request.GET.criteria }}&page={{ page_obj.next_page_number }}"
                               class="pagination-link">next</a>
                        </div>
                        <div class="LinksCatalogue">
                            <a href="?search={{ request.GET.search }}&criteria={{ request.GET.criteria }}&page={{ page_obj.paginator.num_pages }}"
                               class="pagination-link">last &raquo;</a>
                        </div>
                    </div>
                {% endif %}
            </span>
        </div>
    </div>

{% endblock %}

rent_app/rent_app/book_site/templates/book_site/index.html
{% extends "book_site/base.html" %}

{% block content %}

    <div class="container">
        <div class="section"><h2>Why Choose Us?</h2>
            <ul class="home-list">
                <li>Wide Selection: Thousands of titles across various genres—fiction, non-fiction, sci-fi, fantasy,
                    romance, and more.
                </li>
                <li>Free Rentals: Enjoy your favorite books without any cost. All rentals are completely free!</li>
                <li>Convenient Reservations: Reserve your chosen books online and pick them up within 2 days at our
                    shop.
                </li>
                <li>Sustainability: Contribute to a greener planet by renting books.</li>
            </ul>
        </div>
        <div class="section"><h2>How It Works</h2>
            <ol class="home-list-number">
                <li>Browse: Search our extensive catalog and find the book that sparks your interest.</li>
                <li>Reserve: Select your book and place a reservation online. Your book will be ready for pickup within
                    2 days.
                </li>
                <li>Pick Up: Visit our shop to collect your reserved book. Dive into the story and get lost in its
                    pages.
                </li>
                <li>Return: Bring the book back to the shop when you're finished. It's that easy!</li>
            </ol>
        </div>
        <div class="section"><h2>Join Our Community</h2>
            <p class="home-p">Stay updated with the latest book arrivals, reviews, and recommendations. Sign up for our
                newsletter and
                follow us on social media for exclusive offers and bookish content.</p>
        </div>
    </div>

{% endblock %}

rent_app/rent_app/book_site/templates/book_site/info_email_sent.html
{% extends "book_site/base.html" %}

{% block content %}
    <div class="popup">
        <h2>Registration was successful</h2>
        <p>Check your email for a verification link.</p>
    </div>
{% endblock %}

rent_app/rent_app/book_site/templates/book_site/info_verification_success.html
{% extends "book_site/base.html" %}

{% block content %}
    <div class="popup">
        <h2>Your account was activated</h2>
        <p>You can log in now</p>
        <div class="NotLoggedReviewDIV">
            <a href="{% url 'login_redirect' %}" class="btn-btn-info">Log in</a>
        </div>
    </div>
{% endblock %}

rent_app/rent_app/book_site/templates/book_site/navigation.html
<div class="LoginLinkDiv">
    {% if user.is_authenticated %}
        <div class="login-info">Hi {{ user.username }}!</div>
        <form action="{% url 'logout' %}" method="post" class="LogInButton">
            {% csrf_token %}
            <button type="submit" class="logout-button">Log Out</button>
        </form>
    {% else %}
        <div class="login-info">You are not logged in</div>
        <a href="{% url 'login_redirect' %}" class="LogInButton">Log In</a>
    {% endif %}
</div>

<div class="sectionLinksDiv">
    <a href="{% url 'home_redirect' %}" class="sectionLink">Home</a>
    <a href="{% url 'catalogue_redirect' %}" class="sectionLink">Catalogue</a>
    <a href="{% url 'profile_redirect' %}" class="sectionLink">Profile</a>
</div>



rent_app/rent_app/book_site/templates/book_site/popup_reservation_not_logged.html
{% extends "book_site/base.html" %}

{% block content %}
    {% if user.is_authenticated %}

        <div class="popup">
            <h2>{{ message }}</h2>
            <a href="{% url 'catalogue' %}">OK</a>
        </div>
    {% else %}

        <div class="popup">
            <h2>You must be logged in to reserve a book.</h2>
            <p>Please <a href="{% url 'login_redirect' %}">login</a> or <a href="{% url 'register' %}">register</a> to
                continue.
            </p>
        </div>
    {% endif %}

{% endblock %}
